name: Blue-Green Deployment

on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: payment-service
  DOCKER_IMAGE: your-docker-registry/${{ secrets.DOCKER_NAMESPACE }}/nepa-payment-service
  KUBE_NAMESPACE: production

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get image tag
        id: get_tag
        run: echo "tag=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile # Assuming Dockerfile is in root
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ steps.get_tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_green:
    name: Deploy Green Environment
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy Green
        run: |
          # Use a tool like 'envsubst' to substitute variables in k8s manifests
          export IMAGE_TAG=${{ needs.build.outputs.image_tag }}
          export COLOR=green
          
          cat k8s/deployment.yaml | envsubst | kubectl apply -n ${{ env.KUBE_NAMESPACE }} -f -
          
          echo "Waiting for green deployment to be ready..."
          kubectl rollout status deployment/${{ env.SERVICE_NAME }}-${COLOR} -n ${{ env.KUBE_NAMESPACE }} --timeout=5m

  validate_green:
    name: Validate Green Environment
    runs-on: ubuntu-latest
    needs: deploy_green
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Run Health Checks
        run: |
          # Temporarily expose the green service for health checks
          kubectl expose deployment/${{ env.SERVICE_NAME }}-green --name=${{ env.SERVICE_NAME }}-green-temp --port=80 --target-port=3002 -n ${{ env.KUBE_NAMESPACE }}
          
          # Give the service a moment to get an IP
          sleep 15
          
          # Run health check script
          chmod +x ./scripts/health-check.sh
          ./scripts/health-check.sh http://${{ env.SERVICE_NAME }}-green-temp.${{ env.KUBE_NAMESPACE }}.svc.cluster.local/health

      - name: Cleanup temporary service
        if: always()
        run: |
          kubectl delete service/${{ env.SERVICE_NAME }}-green-temp -n ${{ env.KUBE_NAMESPACE }}

  promote_green:
    name: Promote Green to Production
    runs-on: ubuntu-latest
    needs: validate_green
    environment: production
    steps:
      - name: Configure kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Switch production traffic to Green
        run: |
          kubectl patch service ${{ env.SERVICE_NAME }} -n ${{ env.KUBE_NAMESPACE }} -p '{"spec":{"selector":{"app":"${{ env.SERVICE_NAME }}","color":"green"}}}'
          echo "Traffic switched to green environment."

      - name: Decommission Blue environment
        run: |
          echo "Waiting for 1 minute before decommissioning blue..."
          sleep 60
          kubectl delete deployment/${{ env.SERVICE_NAME }}-blue -n ${{ env.KUBE_NAMESPACE }} --ignore-not-found=true
          echo "Blue environment decommissioned."